# Generated by Django 3.2.3 on 2021-06-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_auto_20210606_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('0', 'Open'), ('1', 'Closed')], default=0, max_length=30),
        ),
    ]
