# Generated by Django 3.2.3 on 2021-06-08 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_room_room_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='counter.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.service')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='counter.counter'),
        ),
    ]
